export const trips = [
  {
    id: "1",
    title: "Coastal Italian Adventure",
    location: "Amalfi Coast, Italy",
    image: "/placeholder.svg?height=600&width=800",
    rating: 4.9,
    days: 7,
    people: 2,
    price: 1299,
  },
  {
    id: "2",
    title: "Japanese Culture Exploration",
    location: "Tokyo & Kyoto, Japan",
    image: "/placeholder.svg?height=600&width=800",
    rating: 4.8,
    days: 10,
    people: 2,
    price: 1899,
  },
  {
    id: "3",
    title: "Greek Island Hopping",
    location: "Santorini & Mykonos, Greece",
    image: "/placeholder.svg?height=600&width=800",
    rating: 4.7,
    days: 8,
    people: 4,
    price: 1499,
  },
  {
    id: "4",
    title: "Costa Rican Rainforest Retreat",
    location: "Monteverde, Costa Rica",
    image: "/placeholder.svg?height=600&width=800",
    rating: 4.8,
    days: 6,
    people: 2,
    price: 1099,
  },
  {
    id: "5",
    title: "Moroccan Desert Adventure",
    location: "Marrakech & Sahara, Morocco",
    image: "/placeholder.svg?height=600&width=800",
    rating: 4.6,
    days: 9,
    people: 2,
    price: 1299,
  },
  {
    id: "6",
    title: "New Zealand Nature Expedition",
    location: "South Island, New Zealand",
    image: "/placeholder.svg?height=600&width=800",
    rating: 4.9,
    days: 12,
    people: 2,
    price: 2199,
  },
];
